require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-ssl-check.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - lib/fluent/plugin/in_ssl_check.rb

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Exclude:
    - test/helper.rb

# Naming/MethodParameterName:
#   Exclude:
#     - lib/fluent/plugin/in_ssl_check.rb
