require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/AbcSize:
  Max: 40
  # Exclude:
  #   - lib/fluent/plugin/in_ssl_check.rb

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-ssl-check.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - lib/fluent/plugin/in_ssl_check.rb

Metrics/MethodLength:
  Max: 20

# Naming/MethodParameterName:
#   Exclude:
#     - lib/fluent/plugin/in_ssl_check.rb
